In [2]:
import numpy as np

In [9]:
X_train = np.array([[1, 3, 1], [3, 1, 2]])
y_train = np.array([[9, 11, 7]])
print(f"X_train=\n{X_train}")
print(f"y_train=\n{y_train}")

X_train=
[[1 3 1]
 [3 1 2]]
y_train=
[[ 9 11  7]]


In [6]:
# 4, 2, 1=> 4, 2     2, 4.     1, 2
W1 = np.array([[1, 2], [2, 1], [-1, 2], [-2, 1]])
b1 = np.array([[0], [0], [0], [0]])
W2 = np.array([[1, -1, 2, 3], [-2, 1, 1, 2]])
b2 = np.array([[0], [0]])
W3 = np.array([[1, -1]])
b3 = np.array([[0]])

In [13]:
print(f"W1=\n{W1}")
print(f"b1=\n{b1}")
print(f"W2=\n{W2}")
print(f"b2=\n{b2}")
print(f"W3=\n{W3}")
print(f"b3=\n{b3}")

W1=
[[ 1  2]
 [ 2  1]
 [-1  2]
 [-2  1]]
b1=
[[0]
 [0]
 [0]
 [0]]
W2=
[[ 1 -1  2  3]
 [-2  1  1  2]]
b2=
[[0]
 [0]]
W3=
[[ 1 -1]]
b3=
[[0]]


In [16]:
Z1 = W1 @ X_train + b1
A1 = np.maximum(0, Z1)
Z2 = W2 @ A1 + b2
A2 = np.maximum(0, Z2)
Z3 = W3 @ A2 + b3
A3 = Z3
print(f"Z1=\n{Z1}")
print(f"A1=\n{A1}")
print(f"Z2=\n{Z2}")
print(f"A2=\n{A2}")
print(f"Z3=\n{Z3}")
print(f"A3=\n{A3}")

Z1=
[[ 7  5  5]
 [ 5  7  4]
 [ 5 -1  3]
 [ 1 -5  0]]
A1=
[[7 5 5]
 [5 7 4]
 [5 0 3]
 [1 0 0]]
Z2=
[[15 -2  7]
 [-2 -3 -3]]
A2=
[[15  0  7]
 [ 0  0  0]]
Z3=
[[15  0  7]]
A3=
[[15  0  7]]


In [17]:
m = 3
loss = np.sum((Z3 - y_train) ** 2) / (2 * m)
print(f"Loss = {loss}")

Loss = 26.166666666666668


In [20]:
dZ3 = (Z3 - y_train) / m
dW3 = dZ3 @ A2.T
db3 = np.sum(dZ3, axis=1, keepdims=True)
dA2 = W3.T @ dZ3
dZ2 = dA2 * (Z2 > 0)
dW2 = dZ2 @ A1.T
db2 = np.sum(dZ2, axis=1, keepdims=True)
dA1 = W2.T @ dZ2
dZ1 = dA1 * (Z1 > 0)
dW1 = dZ1 @ X_train.T
db1 = np.sum(dZ1, axis=1, keepdims=True)

In [24]:
print(f"dZ3=\n{dZ3}")
print(f"dW3=\n{dW3}")
print(f"db3=\n{db3}")
print(f"dA2=\n{dA2}")
print(f"dZ2=\n{dZ2}")
print(f"dW2=\n{dW2}")
print(f"db2=\n{db2}")
print(f"dA1=\n{dA1}")
print(f"dZ1=\n{dZ1}")
print(f"dW1=\n{dW1}")
print(f"db1=\n{db1}")

dZ3=
[[ 2.         -3.66666667  0.        ]]
dW3=
[[30.  0.]]
db3=
[[-1.66666667]]
dA2=
[[ 2.         -3.66666667  0.        ]
 [-2.          3.66666667  0.        ]]
dZ2=
[[ 2. -0.  0.]
 [-0.  0.  0.]]
dW2=
[[14. 10. 10.  2.]
 [ 0.  0.  0.  0.]]
db2=
[[2.]
 [0.]]
dA1=
[[ 2.  0.  0.]
 [-2.  0.  0.]
 [ 4.  0.  0.]
 [ 6.  0.  0.]]
dZ1=
[[ 2.  0.  0.]
 [-2.  0.  0.]
 [ 4.  0.  0.]
 [ 6.  0.  0.]]
dW1=
[[ 2.  6.]
 [-2. -6.]
 [ 4. 12.]
 [ 6. 18.]]
db1=
[[ 2.]
 [-2.]
 [ 4.]
 [ 6.]]


In [138]:
X_train = np.array([[1, 3, 1], [3, 1, 2]])
y_train = np.array([[9, 11, 7]])
print(f"X_train=\n{X_train}")
print(f"y_train=\n{y_train}")

X_train=
[[1 3 1]
 [3 1 2]]
y_train=
[[ 9 11  7]]


In [136]:
# 4, 2     2, 4     1, 2
W1 = np.array([[1, 2], [2, 1], [-1, 2], [-2, 1]])
b1 = np.array([[0], [0], [0], [0]])
W2 = np.array([[4, 1, 2, 3], [4, 1, 2, 3]])
b2 = np.array([[0], [0]])
W3 = np.array([[1, 2]])
b3 = np.array([[0]])

In [137]:
print(f"W1=\n{W1}")
print(f"b1=\n{b1}")
print(f"W2=\n{W2}")
print(f"b2=\n{b2}")
print(f"W3=\n{W3}")
print(f"b3=\n{b3}")

W1=
[[ 1  2]
 [ 2  1]
 [-1  2]
 [-2  1]]
b1=
[[0]
 [0]
 [0]
 [0]]
W2=
[[4 1 2 3]
 [4 1 2 3]]
b2=
[[0]
 [0]]
W3=
[[1 2]]
b3=
[[0]]


In [139]:
Z1 = W1 @ X_train + b1
A1 = np.maximum(0, Z1)
Z2 = W2 @ A1 + b2
A2 = np.maximum(0, Z2)
Z3 = W3 @ A2 + b3
A3 = Z3
print(f"Z1=\n{Z1}")
print(f"A1=\n{A1}")
print(f"Z2=\n{Z2}")
print(f"A2=\n{A2}")
print(f"Z3=\n{Z3}")
print(f"A3=\n{A3}")

Z1=
[[ 7  5  5]
 [ 5  7  4]
 [ 5 -1  3]
 [ 1 -5  0]]
A1=
[[7 5 5]
 [5 7 4]
 [5 0 3]
 [1 0 0]]
Z2=
[[46 27 30]
 [46 27 30]]
A2=
[[46 27 30]
 [46 27 30]]
Z3=
[[138  81  90]]
A3=
[[138  81  90]]


In [140]:
m = 3
loss = np.sum((Z3 - y_train) ** 2) / (2 * m)
print(f"Loss = {loss}")

Loss = 4738.333333333333


In [141]:
dZ3 = (Z3 - y_train) / m
dW3 = dZ3 @ A2.T
db3 = np.sum(dZ3, axis=1, keepdims=True)
dA2 = W3.T @ dZ3
dZ2 = dA2 * (Z2 > 0)
dW2 = dZ2 @ A1.T
db2 = np.sum(dZ2, axis=1, keepdims=True)
dA1 = W2.T @ dZ2
dZ1 = dA1 * (Z1 > 0)
dW1 = dZ1 @ X_train.T
db1 = np.sum(dZ1, axis=1, keepdims=True)

In [142]:
print(f"dZ3=\n{dZ3}")
print(f"dW3=\n{dW3}")
print(f"db3=\n{db3}")
print(f"dA2=\n{dA2}")
print(f"dZ2=\n{dZ2}")
print(f"dW2=\n{dW2}")
print(f"db2=\n{db2}")
print(f"dA1=\n{dA1}")
print(f"dZ1=\n{dZ1}")
print(f"dW1=\n{dW1}")
print(f"db1=\n{db1}")

dZ3=
[[43.         23.33333333 27.66666667]]
dW3=
[[3438. 3438.]]
db3=
[[94.]]
dA2=
[[43.         23.33333333 27.66666667]
 [86.         46.66666667 55.33333333]]
dZ2=
[[43.         23.33333333 27.66666667]
 [86.         46.66666667 55.33333333]]
dW2=
[[ 556.  489.  298.   43.]
 [1112.  978.  596.   86.]]
db2=
[[ 94.]
 [188.]]
dA1=
[[516. 280. 332.]
 [129.  70.  83.]
 [258. 140. 166.]
 [387. 210. 249.]]
dZ1=
[[516. 280. 332.]
 [129.  70.  83.]
 [258.   0. 166.]
 [387.   0.   0.]]
dW1=
[[1688. 2492.]
 [ 422.  623.]
 [ 424. 1106.]
 [ 387. 1161.]]
db1=
[[1128.]
 [ 282.]
 [ 424.]
 [ 387.]]


In [3]:
# 4, 2, 1=> 4, 2     2, 4.     1, 2
W1 = np.array([[0, 0], [0, 0], [0, 0], [0, 0]])
b1 = np.array([[0], [0], [0], [0]])
W2 = np.array([[0, 0, 0, 0], [0, 0, 0, 0]])
b2 = np.array([[0], [0]])
W3 = np.array([[0, 0]])
b3 = np.array([[0.1]])