In [72]:
test = "Hello World"
print("test = " + test)

test = Hello World


In [73]:
import math
from public_tests import *

In [74]:
def basic_sigmoid(x):
    return 1 / (1 + math.exp(-x)) if x >= 0 else math.exp(x) / (1 + math.exp(x))

In [75]:
print("basic_sigmoid(1) = " + str(basic_sigmoid(1)))

basic_sigmoid(1) = 0.7310585786300049


In [76]:
import numpy as np

In [77]:
t_x = np.array([1, 2, 3])
print(np.exp(t_x))

[ 2.71828183  7.3890561  20.08553692]


In [78]:
t_x = np.array([1, 2, 3])
print(t_x + 3)

[4 5 6]


In [79]:
def sigmoid(x):
    x = np.asarray(x, dtype=np.float64)
    return np.where(x >= 0, 1 / (1 + np.exp(-x)), np.exp(x) / (1 + np.exp(x)))

In [80]:
t_x = np.array([1, 2, 3])
print("sigmoid(t_x) = " + str(sigmoid(t_x)))
sigmoid_test(sigmoid)

sigmoid(t_x) = [0.73105858 0.88079708 0.95257413]
 All tests passed.


In [81]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

In [82]:
t_x = np.array([1, 2, 3])
print("sigmoid_derivative(t_x) = " + str(sigmoid_derivative(t_x)))

sigmoid_derivative_test(sigmoid_derivative)

sigmoid_derivative(t_x) = [0.19661193 0.10499359 0.04517666]
 All tests passed.


In [83]:
def image2vector(image):
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return v

In [84]:
t_image = np.array(
    [
        [[0.67826139, 0.29380381], [0.90714982, 0.52835647], [0.4215251, 0.45017551]],
        [[0.92814219, 0.96677647], [0.85304703, 0.52351845], [0.19981397, 0.27417313]],
        [[0.60659855, 0.00533165], [0.10820313, 0.49978937], [0.34144279, 0.94630077]],
    ]
)

print("image2vector(image) = " + str(image2vector(t_image)))

image2vector_test(image2vector)

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
 All tests passed.


In [85]:
def normalize_rows(x):
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    return x / x_norm

In [86]:
x = np.array([[0.0, 3.0, 4.0], [1.0, 6.0, 4.0]])
print("normalizeRows(x) = " + str(normalize_rows(x)))

normalizeRows_test(normalize_rows)

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
 All tests passed.


In [87]:
def softmax(x):
    x_shifted = x - np.max(x, axis=1, keepdims=True)
    x_shifted_exp = np.exp(x_shifted)
    x_shifted_norm = np.sum(x_shifted_exp, axis=1, keepdims=True)
    return x_shifted_exp / x_shifted_norm

In [88]:
t_x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0, 0]])
print("softmax(x) = " + str(softmax(t_x)))
softmax_test(softmax)

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
 All tests passed.


In [89]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print(
    "dot = "
    + str(dot)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i][j] = x1[i] * x2[j]
toc = time.process_time()
print(
    "outer = "
    + str(outer)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print(
    "elementwise multiplication = "
    + str(mul)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)
W = np.random.rand(3, len(x1))  # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i, j] * x1[j]
toc = time.process_time()
print(
    "gdot = "
    + str(gdot)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)

dot = 278
 ----- Computation time = 0.042999999999793204ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [90]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1, x2)
toc = time.process_time()
print(
    "dot = "
    + str(dot)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1, x2)
toc = time.process_time()
print(
    "outer = "
    + str(outer)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1, x2)
toc = time.process_time()
print(
    "elementwise multiplication = "
    + str(mul)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W, x1)
toc = time.process_time()
print(
    "gdot = "
    + str(dot)
    + "\n ----- Computation time = "
    + str(1000 * (toc - tic))
    + "ms"
)

dot = 278
 ----- Computation time = 0.04600000000021254ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.09399999999981645ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.02199999999996649ms
gdot = [29.4339463  30.93941899 22.860830

In [91]:
def L1(yhat, y):
    loss = np.sum(np.abs(yhat - y))
    return loss

In [92]:
yhat = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))

L1_test(L1)

L1 = 1.1
 All tests passed.


In [93]:
def L2(yhat, y):
    e = yhat - y
    loss = np.dot(e, e)  # equivalent to loss = np.sum(e ** 2)
    # loss = np.sum(e ** 2)
    return loss

In [94]:
yhat = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))

L2_test(L2)

L2 = 0.43
 All tests passed.
