In [1]:
import numpy as np

In [2]:
W = np.array([[3, 1], [5, 7], [2, 5]])
W_T = W.T
W_T__W = np.matmul(W_T, W)
print(f"W = \n{W}")
print(f"W_T = \n{W_T}")
print(f"W_T__W = \n{W_T__W}")

W = 
[[3 1]
 [5 7]
 [2 5]]
W_T = 
[[3 5 2]
 [1 7 5]]
W_T__W = 
[[38 48]
 [48 75]]


In [28]:
x = np.array([1, 2]).reshape(-1, 1)
print(x)

[[1]
 [2]]


In [7]:
z = np.matmul(W_T__W, x)
print(z)

[[134]
 [198]]


In [29]:
eigenvalues, eigenvectors = np.linalg.eigh(W_T__W)
# Print the results
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

for col in eigenvectors.T:
    print(np.linalg.norm(col))
# 1.0
# 1.0

Eigenvalues: [  5.05828541 107.94171459]

Eigenvectors:
 [[-0.82450904  0.56584878]
 [ 0.56584878  0.82450904]]
0.9999999999999999
0.9999999999999999


In [37]:
x = np.array([2, 1]).reshape(-1, 1)
y = np.matmul(W_T__W, x)

P = eigenvectors  # columns are eigenvectors
x_in_eigenspace = P.T @ x

print("y = W_T__W @ x:\n", y)
print("\nx in eigenspace:\n", x_in_eigenspace)

y = W_T__W @ x:
 [[124]
 [171]]

x in eigenspace:
 [[-1.0831693]
 [ 1.9562066]]


In [40]:
Lambda = np.diag(eigenvalues)
y_via_eigenspace = P @ Lambda @ x_in_eigenspace
print("\ny reconstructed via eigenspace:\n", y_via_eigenspace)


y reconstructed via eigenspace:
 [[124.]
 [171.]]


In [45]:
U, S, V_T = np.linalg.svd(W)
print("U:\n", U)
print("\nS:", S)
print("\nV_T:\n", V_T)
print(f"Eigenvectors :\n{eigenvectors}")
W__W_T = np.dot(W, W_T)
print(f"W__W_T = \n{W__W_T}")
eigen_val2, eigen_vec2 = np.linalg.eigh(W__W_T)
print(f"eigen_val2 = {eigen_val2}")
print(f"eigen_vect2 = {eigen_vec2}")

U:
 [[-0.2427504   0.84821019  0.47075654]
 [-0.82783647  0.0718538  -0.55634864]
 [-0.50572623 -0.52476329  0.68473679]]

S: [10.38950021  2.24906323]

V_T:
 [[-0.56584878 -0.82450904]
 [ 0.82450904 -0.56584878]]
Eigenvectors :
[[-0.82450904  0.56584878]
 [ 0.56584878  0.82450904]]
W__W_T = 
[[10 22 11]
 [22 74 45]
 [11 45 29]]
eigen_val2 = [4.03563753e-16 5.05828541e+00 1.07941715e+02]
eigen_vect2 = [[ 0.47075654 -0.84821019 -0.2427504 ]
 [-0.55634864 -0.0718538  -0.82783647]
 [ 0.68473679  0.52476329 -0.50572623]]


In [51]:
x = np.array([2, 1]).reshape(-1, 1)
z = np.dot(W, x)
print(f"z = \n{z}")
Sigma = np.zeros((W.shape[0], W.shape[1]))
np.fill_diagonal(Sigma, S)
z_via_SVD = U @ Sigma @ V_T @ x
print(f"z_via_SVD = \n{z_via_SVD}")

z = 
[[ 7]
 [17]
 [ 9]]
z_via_SVD = 
[[ 7.]
 [17.]
 [ 9.]]


In [55]:
x = np.array([7, 5]).reshape(-1, 1)
z = np.dot(W, x)
print(f"z = \n{z}")

z = 
[[26]
 [70]
 [39]]
